# Generated by Django 5.2.1 on 2025-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_borrowtransaction_borrowed_at_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('RESERVED', 'Reserved'), ('LOST', 'Lost')], default='AVAILABLE', max_length=10),
        ),
    ]
